Repository Ttatta-org/Ttatta_BE, pull requests merged in 2025-02, with the labels that each got.

#78 [Feat] 일기 사진 교체 기능 구현
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
Labels: ✨ Feature

#76 [Feat] 검색 시 해당 일기 조회 API
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#82 [Feat] 회원 정보 관련 API 수정
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#85 [Feat] 로그아웃 api기능 구현
  src/main/java/TtattaBackend/ttatta/config/security/JwtAuthenticationFilter.java
  src/main/java/TtattaBackend/ttatta/jwt/JwtUtils.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
Labels: ✨ Feature

#52 [Feat] 지도 발자국 표시를 위한 일기 조회 API, 최신 일기 반환 반영
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Diaries.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#86 [Feat] 일기 지도 조회 API
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#87 [Feat] 아이템 생성, 구매, 착용 api
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/config/security/JwtAuthenticationFilter.java
  src/main/java/TtattaBackend/ttatta/converter/ItemConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Items.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/domain/enums/CharacterType.java
  src/main/java/TtattaBackend/ttatta/domain/mapping/OwnedItems.java
  src/main/java/TtattaBackend/ttatta/repository/ItemRepository.java
  src/main/java/TtattaBackend/ttatta/repository/OwnedItemRepository.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemCommandService.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ItemController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ItemRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/ItemResponseDTO.java
Labels: ✨ Feature

#90 [Feat] 카테고리 별 발자국 조회 및 일기 조회
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
Labels: ✨ Feature

#92 [Feat] Item 도메인 수정 및 ENUM 추가
  src/main/java/TtattaBackend/ttatta/domain/Items.java
  src/main/java/TtattaBackend/ttatta/domain/enums/BodyPart.java
Labels: ✨ Feature

#94 [Feat] 아이템 해제 API 구현
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/converter/ItemConverter.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemCommandService.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ItemController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ItemResponseDTO.java
Labels: ✨ Feature

#99 [Feat] 전체 일기 날짜 중복없이 조회 api
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#103 [Feat] 회원 정보 조회 API 수정
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#96 [Feat] 미소유 아이템(shop) 조회 기능 구현
  src/main/java/TtattaBackend/ttatta/converter/ItemConverter.java
  src/main/java/TtattaBackend/ttatta/repository/ItemRepository.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemQueryService.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ItemController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ItemResponseDTO.java
Labels: ✨ Feature

#104 [Feat] 소유 아이템(myitem) 조회 기능 구현
  src/main/java/TtattaBackend/ttatta/converter/ItemConverter.java
  src/main/java/TtattaBackend/ttatta/repository/ItemRepository.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemQueryService.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ItemController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ItemResponseDTO.java
Labels: ✨ Feature

#107 [Feat] 금일 챌린지 조회 api 구현
  src/main/java/TtattaBackend/ttatta/converter/ChallengeConverter.java
  src/main/java/TtattaBackend/ttatta/repository/ChallengeRepository.java
  src/main/java/TtattaBackend/ttatta/service/ChallengeService/ChallengeCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/service/ChallengeService/ChallengeQueryService.java
  src/main/java/TtattaBackend/ttatta/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ChallengeController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ChallengeResponeseDTO.java
Labels: ✨ Feature

#115 [Feat] 착용한 아이템 반환 API
  src/main/java/TtattaBackend/ttatta/converter/ItemConverter.java
  src/main/java/TtattaBackend/ttatta/repository/ItemRepository.java
  src/main/java/TtattaBackend/ttatta/repository/OwnedItemRepository.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemQueryService.java
  src/main/java/TtattaBackend/ttatta/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ItemController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ItemResponseDTO.java
Labels: ✨ Feature

#111 [Feat] 가장 최근에 실패한 5개의 챌린지 조회 api 구현
  src/main/java/TtattaBackend/ttatta/converter/ChallengeConverter.java
  src/main/java/TtattaBackend/ttatta/repository/ChallengeRepository.java
  src/main/java/TtattaBackend/ttatta/service/ChallengeService/ChallengeQueryService.java
  src/main/java/TtattaBackend/ttatta/service/ChallengeService/ChallengeQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/ChallengeController.java
  src/main/java/TtattaBackend/ttatta/web/dto/ChallengeResponeseDTO.java
Labels: ✨ Feature

#117 [Feat] response body에 일기 카테고리 id 필드 추가
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#120 [Feat] 카카오톡 open Id 유효성 검사
  build.gradle
  src/main/java/TtattaBackend/ttatta/TtattaApplication.java
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/config/KaKaoOauthConfig.java
  src/main/java/TtattaBackend/ttatta/config/KakaoInfoConfig.java
  src/main/java/TtattaBackend/ttatta/config/RedisCacheConfig.java
  src/main/java/TtattaBackend/ttatta/config/security/JwtAuthenticationFilter.java
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/oidc/JwtOIDCProvider.java
  src/main/java/TtattaBackend/ttatta/oidc/KakaoInfoErrorDecoder.java
  src/main/java/TtattaBackend/ttatta/oidc/KakaoOauthClient.java
  src/main/java/TtattaBackend/ttatta/oidc/KakaoOauthHelper.java
  src/main/java/TtattaBackend/ttatta/oidc/OIDCDecodePayload.java
  src/main/java/TtattaBackend/ttatta/oidc/OIDCPublicKeyDto.java
  src/main/java/TtattaBackend/ttatta/oidc/OIDCPublicKeyResponse.java
  src/main/java/TtattaBackend/ttatta/oidc/OauthInfo.java
  src/main/java/TtattaBackend/ttatta/oidc/OauthOIDCHelper.java
  src/main/java/TtattaBackend/ttatta/oidc/OauthProperties.java
  src/main/java/TtattaBackend/ttatta/oidc/OauthProvider.java
  src/main/java/TtattaBackend/ttatta/oidc/UnlinkKaKaoTarget.java
  src/main/java/TtattaBackend/ttatta/repository/UserRepository.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#122 [Feat] 카카오 회원가입 API
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#126 [Feat] 카카오 로그인 Id token 검증 api와 카카오 회원가입 api의 request body에 있는 openId값을 header로 변경
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
Labels: ✨ Feature

#127 [Feat] 이메일 인증 API 구현
  build.gradle
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/config/security/JwtAuthenticationFilter.java
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/repository/UserRepository.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#129 [Deploy] 배포 테스트
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
Labels: 🌏 Deploy

#134 [Feat] 회원가입 시 아이디 입력 조건을 '아이디는 6 ~ 15자이어야 합니다.'로 변경
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
Labels: ✨ Feature

#139 [Feat] 인증 메일 html 적용
  build.gradle
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/resources/img/ttatta_logo.png
  src/main/resources/templates/verification-email.html
Labels: ✨ Feature

#140 [Refactor] 인증 메일 html 수정
  src/main/resources/templates/verification-email.html
Labels: 🔨 Refactor

#138 [Feat] s3 이미지 리사이징 및 사진 회전 수정
  build.gradle
  src/main/java/TtattaBackend/ttatta/aws/s3/AmazonS3Manager.java
  src/main/java/TtattaBackend/ttatta/aws/s3/CustomMultipartFile.java
Labels: ✨ Feature

#143 Revert "[Feat] s3 이미지 리사이징 및 사진 회전 수정"
  build.gradle
  src/main/java/TtattaBackend/ttatta/aws/s3/AmazonS3Manager.java
  src/main/java/TtattaBackend/ttatta/aws/s3/CustomMultipartFile.java
Labels: 🐞 BugFix

#144 [Feat] 일기 리사이징 기능 구현
  build.gradle
  src/main/java/TtattaBackend/ttatta/aws/s3/AmazonS3Manager.java
  src/main/java/TtattaBackend/ttatta/aws/s3/CustomMultipartFile.java
Labels: 🐞 BugFix

#147 [Fix] 관리자 API 경로 수정
  src/main/java/TtattaBackend/ttatta/config/security/JwtAuthenticationFilter.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
Labels: 🐞 BugFix

#151 [Feat] 회원가입 시 1000 포인트 추가 (시연용)
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
Labels: ✨ Feature
