Repository Ttatta-org/Ttatta_BE, pull requests merged in 2025-01, with the labels that each got.

#6 [Chore] swagger 세팅
  build.gradle
  src/main/java/TtattaBackend/ttatta/config/SwaggerConfig.java
Labels: 🥰 Chore

#8 [Feat] 테스트 유저 생성 개발용 API 구현
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Diaries.java
  src/main/java/TtattaBackend/ttatta/domain/DiaryCategories.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/repository/UserRepository.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#11 [Chore] commit 템플릿 추가
  .gitmessage.txt
Labels: 🥰 Chore

#16 [Feat] 일반 회원가입, 일반 로그인 API 구현
  build.gradle
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/SuccessStatus.java
  src/main/java/TtattaBackend/ttatta/config/security/CustomAuthenticationProvider.java
  src/main/java/TtattaBackend/ttatta/config/security/CustomDetailsService.java
  src/main/java/TtattaBackend/ttatta/config/security/CustomUserDetailsService.java
  src/main/java/TtattaBackend/ttatta/config/security/SecurityConfig.java
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/repository/UserRepository.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#15 [Feat] 카테고리 생성 API 구현
  src/main/java/TtattaBackend/ttatta/converter/DiaryCategoryConverter.java
  src/main/java/TtattaBackend/ttatta/domain/DiaryCategories.java
  src/main/java/TtattaBackend/ttatta/domain/enums/CategoryColor.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryCategoryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryResponseDTO.java
  src/main/resources/application.properties
Labels: ✨ Feature

#18 [Feat] 일기 작성 API 구현 및 S3 설정
  build.gradle
  src/main/java/TtattaBackend/ttatta/aws/s3/AmazonS3Manager.java
  src/main/java/TtattaBackend/ttatta/config/AmazonConfig.java
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Diaries.java
  src/main/java/TtattaBackend/ttatta/domain/DiaryPhotos.java
  src/main/java/TtattaBackend/ttatta/domain/Uuid.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryPhotosRepository.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/repository/UuidRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryPhotoService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryPhotoServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#22 [Feat] 일기 관련 controller dto 구현
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryPhotoService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryPhotoServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#21 [Feat] 카테고리 관련 API의 DTO & controller
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryResponseDTO.java
Labels: ✨ Feature

#24 [Feat] 미개발 user관련 api의 controller 및 dto 작성
  src/main/java/TtattaBackend/ttatta/domain/enums/IsSame.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#27 [Feat] validator annotation 예외처리 및 회원가입, 로그인 예외처리
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/apiPayload/exception/ExceptionAdvice.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/validation/annotation/ExistUser.java
  src/main/java/TtattaBackend/ttatta/validation/validator/ExistUserValidator.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
Labels: ✨ Feature

#29 [Refactor] diaries entity의 위도 경도 column의 type을 String에서 double로 변경
  src/main/java/TtattaBackend/ttatta/domain/Diaries.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
Labels: 🔨 Refactor

#36 [Feat] 카테고리 수정 API
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/converter/DiaryCategoryConverter.java
  src/main/java/TtattaBackend/ttatta/domain/DiaryCategories.java
  src/main/java/TtattaBackend/ttatta/domain/enums/CategoryColor.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/validation/annotation/ExistDiaryCategoryColor.java
  src/main/java/TtattaBackend/ttatta/validation/validator/ExistDiaryCategoryColorValidator.java
  src/main/java/TtattaBackend/ttatta/validation/validator/ExistDiaryCategoryValidator.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryResponseDTO.java
Labels: ✨ Feature

#39 [Feat] 모든 카테고리 삭제 API
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
Labels: ✨ Feature

#41 deploy: #33 CI/CD 테스트
  .github/workflows/dev_deploy.yml
Labels: 🌏 Deploy

#34 [Refactor] 일기 사진 수 변경 및 매핑 수정
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
Labels: 🔨 Refactor

#42 [Feat] 카테고리 삭제 API
  src/main/java/TtattaBackend/ttatta/domain/DiaryCategories.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryCategoryRepository.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
Labels: ✨ Feature

#49 [Feat] 일기 내용 수정 API 및 일기 카테고리 수정
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Diaries.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryCategoryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#54 [Fix] 카테고리 삭제 api 수정
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
Labels: 🐞 BugFix

#51 [Feat] 카테고리별 일기 개수 조회 및 전체 일기 개수 조회
  src/main/java/TtattaBackend/ttatta/converter/DiaryCategoryConverter.java
  src/main/java/TtattaBackend/ttatta/domain/DiaryCategories.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryCategoryRepository.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryResponseDTO.java
Labels: ✨ Feature

#44 [Feat] 일반 로그인 성공이후 jwt토큰(accessToken) 발급 및 api요청 시 jwt토큰 검증 처리 기능 spring security와 함께 구현
  build.gradle
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/config/RedisConfig.java
  src/main/java/TtattaBackend/ttatta/config/SwaggerConfig.java
  src/main/java/TtattaBackend/ttatta/config/security/JwtAuthenticationFilter.java
  src/main/java/TtattaBackend/ttatta/config/security/SecurityConfig.java
  src/main/java/TtattaBackend/ttatta/config/security/SecurityUtil.java
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/jwt/JwtUtils.java
  src/main/java/TtattaBackend/ttatta/jwt/exception/CustomExpiredJwtException.java
  src/main/java/TtattaBackend/ttatta/jwt/exception/CustomJwtException.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#47 [Feat] 회원가입 중 아이디 중복 확인 API 구현
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/domain/enums/IsAvailable.java
  src/main/java/TtattaBackend/ttatta/domain/enums/IsSame.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandService.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/UserController.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserResponseDTO.java
Labels: ✨ Feature

#57 [Fix] errorstatus enum에 ';'대신 ','가 들어가야 하는 것 수정
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
Labels: 🐞 BugFix

#61 [Deploy] CI/CD 설정
  .github/workflows/dev_deploy.yml
  .github/workflows/github-actions.yml
  Dockerfile
Labels: 🌏 Deploy

#62 [Fix] github-action.yml 들여쓰기 수정
  .github/workflows/github-actions.yml
Labels: 🐞 BugFix

#63 [Fix] github-action.yml 수정
  .github/workflows/github-actions.yml
Labels: 🐞 BugFix

#64 [Refactor] userId body 삭제 및 token 처리
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
Labels: 🔨 Refactor

#60 [Refactor] 카테고리 유저id -> 토큰
  src/main/java/TtattaBackend/ttatta/apiPayload/code/status/ErrorStatus.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryCategoryRepository.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: 🔨 Refactor

#66 [Feat] 일반 회원가입 시 요청에 이름과 이메일 추가
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/domain/Users.java
  src/main/java/TtattaBackend/ttatta/web/dto/UserRequestDTO.java
Labels: ✨ Feature

#68 [Feat] 회원가입 시 회원마다 일상 카테고리 추가 기능 구현 완료
  src/main/java/TtattaBackend/ttatta/converter/UserConverter.java
  src/main/java/TtattaBackend/ttatta/service/UserService/UserCommandServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryRequestDTO.java
Labels: ✨ Feature

#70 [Feat] 일기 보관함 일기 조회 및 캘린더 클릭 시 해당 날짜 일기 조회
  src/main/java/TtattaBackend/ttatta/converter/DiaryConverter.java
  src/main/java/TtattaBackend/ttatta/repository/DiaryRepository.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryRequestDTO.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryResponseDTO.java
Labels: ✨ Feature

#72 [Refator] 다이어리 카테고리 전반적인 수정
  src/main/java/TtattaBackend/ttatta/converter/DiaryCategoryConverter.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryQueryService.java
  src/main/java/TtattaBackend/ttatta/service/DiaryCategoryService/DiaryCategoryQueryServiceImpl.java
  src/main/java/TtattaBackend/ttatta/web/controller/DiaryCategoryController.java
  src/main/java/TtattaBackend/ttatta/web/dto/DiaryCategoryResponseDTO.java
Labels: 🔨 Refactor
